Popov\ZfcFields\Model\FieldsPages:
  type: entity
  repositoryClass: Popov\ZfcFields\Model\Repository\FieldsPagesRepository
  table: fields_pages
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
      options:
        unsigned: true
    fieldsId:
      type: integer
      options:
        unsigned: true
    pagesId:
      type: integer
      options:
        unsigned: true
    position:
      type: integer
  manyToOne:
    fields:
      targetEntity: Popov\ZfcFields\Model\Fields
      inversedBy: fieldsPages
      joinColumn:
        name: fieldsId
        referencedColumnName: id
    pages:
      targetEntity: Popov\ZfcFields\Model\Pages
      inversedBy: fieldsPages
      joinColumn:
        name: pagesId
        referencedColumnName: id