Popov\ZfcFields\Model\Pages:
  type: entity
  table: pages
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
      options:
        unsigned: true
    page:
      type: string
      length: 255
  oneToMany:
    fieldsPages:
      targetEntity: Popov\ZfcFields\Model\FieldsPages
      mappedBy: pages
    permissionSettingsPages:
      targetEntity: Popov\ZfcPermission\Model\PermissionSettingsPages
      mappedBy: pages